### ISSUE TITLE
No notification added when notification screen is active and a new notification arrives

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#117]
Looks like a UI update issue.

https://cloud.kampert.synology.me/s/inxo6zJBWd5XBQm

**Comment by jakkra** [comment]
Yeah, it's not a bug, it's just not implemented. The notification app is very simple.
https://github.com/jakkra/ZSWatch/issues/70

**Comment by Kampi** [comment]
Great! I assign this issue to me and implemented it with the notification stuff.
