### ISSUE TITLE
Enclosure

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch#136]
Hello, I would like to ask, did you not upload the 3D file of the enclosure? I didn't find it. Thank you for your reply!

**Comment by Kampi** [comment]
Hi @DREAM669 

Please check the `cad` directory in the hardware repository.
https://github.com/jakkra/ZSWatch-HW

**Comment by DREAM669** [comment]
Okay, I understand. Thank you!

**Comment by jakkra** [comment]
@DREAM669 Also take a look here for more info. I have started with an assembly and printing guide, but not finished.

https://github.com/jakkra/ZSWatch/wiki/Case-and-3D-printing
