### ISSUE TITLE
Add C02 output from BSEC2

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#137]
Add here https://github.com/jakkra/ZSWatch/blob/main/app/drivers/sensor/bme68x_iaq/bosch_bme68x_iaq.c#L28
And read it out from BSEC2 library.
Add the necessary functions, should be same as the IAQ

Here are all features output by BSEC: https://github.com/boschsensortec/Bosch-BSEC2-Library/blob/master/src/inc/bsec_datatypes.h#L199

We could add more also.

**Comment by Kampi** [comment]
On it :)
Should be a quick one

**Comment by jakkra** [comment]
> On it :) Should be a quick one. Let´s add VOC too?

Yes, add anything relevent!
