### ISSUE TITLE
Integrate Bosch BSX Lite library for 6-DOF sensor fusion

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#138]
With this we can utilize Bosch library for fusion for Accel + Gyro to get Roll, Yaw  and Pitch angles.

This is what the library can output for us, can be used for some nice stuff!
![image](https://github.com/jakkra/ZSWatch/assets/4318648/1f831c53-f004-4254-bcb5-e1da3b28c951)

https://www.bosch-sensortec.com/software-tools/software/sensor-fusion-software-bsx/

**Comment by ldab** [comment]
On it 🫡

**Comment by ldab** [comment]
How do we deal with licensing? Bosch ask for license agreement, perhaps we can't share openly? like people need to go there and click with their info?

**Comment by jakkra** [comment]
Yes off by default (kconfig) and user need to download and put in a specific folder. For the BSEC2 it's solved a bit easier, even though I think it's the same license. But bosch have it on Github, which means we cannot automatically clone it, but using a west command see here https://github.com/jakkra/ZSWatch/blob/main/GETTING_STARTED.md#use-bosch-bsec2 and this is how nordic also does it, so assumed to be fine.

For now at least start with user need to download and put it in a specific folder, and then enable using kconfig

**Comment by ldab** [comment]
> Yes off by default (kconfig) and user need to download and put in a specific folder. For the BSEC2 it's solved a bit easier, even though I think it's the same license. But bosch have it on Github, which means we cannot automatically clone it, but using a west command see here https://github.com/jakkra/ZSWatch/blob/main/GETTING_STARTED.md#use-bosch-bsec2 and this is how nordic also does it, so assumed to be fine.
> 
> For now at least start with user need to download and put it in a specific folder, and then enable using kconfig

Cool, URL on readme is broken btw

**Comment by jakkra** [comment]
> > Yes off by default (kconfig) and user need to download and put in a specific folder. For the BSEC2 it's solved a bit easier, even though I think it's the same license. But bosch have it on Github, which means we cannot automatically clone it, but using a west command see here https://github.com/jakkra/ZSWatch/blob/main/GETTING_STARTED.md#use-bosch-bsec2 and this is how nordic also does it, so assumed to be fine.
> > For now at least start with user need to download and put it in a specific folder, and then enable using kconfig
> 
> Cool, URL on readme is broken btw

Yep, already fixed :)

**Comment by ldab** [comment]
BSXlite is not on GitHub. Do you have some features that needs it now? If not then I’ll work on the speedometer thing before as 
1. this BSXlite may need more thoughts 
2. and I also think it will clash with the pedometer
3. It does not give the heading speed anyway

**Comment by jakkra** [comment]
> BSXlite is not on GitHub. Do you have some features that needs it now? If not then I’ll work on the speedometer thing before as
> 
> 1. this BSXlite may need more thoughts
> 2. and I also think it will clash with the pedometer
> 3. It does not give the heading speed anyway

Yeah no problem, nothing really that needs it for now.

**Comment by jakkra** [comment]
Just found this: https://github.com/xioTechnologies/Fusion

It's a sensor fusion library that also takes magnetometer data (compared with that BSX Lite does). 

That would give us absolute orientation, not just relative which BSX Lite does. Also this library is open source. Utilizing a full 9-Axis.

Looks quite undertandable and seems quite easy to use: https://github.com/xioTechnologies/Fusion/blob/main/Examples/Advanced/main.c 

More info: https://x-io.co.uk/open-source-imu-and-ahrs-algorithms/

**Comment by ldab** [comment]
Sounds promising, generally those sensor fusion needs raw sensor input quite frequently, do you think it would interfere with Pedometer?

**Comment by jakkra** [comment]
> Sounds promising, generally those sensor fusion needs raw sensor input quite frequently, do you think it would interfere with Pedometer?

Why would is clash with pedometer, that's just a built in feature of the IMU. We fetch accel and gyro data simultaniously.

**Comment by ldab** [comment]
> > Sounds promising, generally those sensor fusion needs raw sensor input quite frequently, do you think it would interfere with Pedometer?
> 
> Why would is clash with pedometer, that's just a built in feature of the IMU. We fetch accel and gyro data simultaniously.

I don't know just guessing, that if we change the rate to say 100Hz, the pedometer function does not work or something like that

**Comment by jakkra** [comment]
> > > Sounds promising, generally those sensor fusion needs raw sensor input quite frequently, do you think it would interfere with Pedometer?
> > 
> > 
> > Why would is clash with pedometer, that's just a built in feature of the IMU. We fetch accel and gyro data simultaniously.
> 
> I don't know just guessing, that if we change the rate to say 100Hz, the pedometer function does not work or something like that

I think it's fine, I only saw requirements on minimal rate.

**Comment by jakkra** [comment]
Closing as it's implemented using Fusion library.
