### ISSUE TITLE
Jlink&IIC

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch#140]
Hello, I have encountered two issues.
First question: How can I use JLink for debugging in VS code? What are the minimum pins that JLink needs to connect to?
The second question: Reading sensor information through IIC and calling the IIC read interface resulted in an incorrect return value. What is the approximate reason?

**Comment by Kampi** [comment]
Hi @DREAM669 
1) SWD needs
- SWDCLK
- SWDIO
- GND
- VTarget
- VCC on the target
You can debug by using the Debug function of the nRF Connect Plugin in VS Code (NOT the regular debug!)

2) Hard to say. Can you please share your code?

**Comment by DREAM669** [comment]
<img width="929" alt="捕获" src="https://github.com/jakkra/ZSWatch/assets/56341360/ba9ec26e-938e-454b-88de-a74555925096">

**Comment by DREAM669** [comment]
I clicked the debug button, then it showed no connected device found.

**Comment by Kampi** [comment]
It looks like that no SWD target is found. Also your debugger looks strange because of the loading circle. 
Please do the following:
- What kind of debugger do you use?
- Does the debugger gets loaded correctly when no target is attached? Restart VS Code to be sure
- Can you expand the debugger menu and see a target?

**Comment by DREAM669** [comment]
> It looks like no SWD target is found. Also, your debugger looks strange because of the loading circle. Please do the following:
> 
> * What kind of debugger do you use?
I am using J-Link as shown in the following image.
![下载](https://github.com/jakkra/ZSWatch/assets/56341360/337f2431-310a-4361-a337-3c91c40710e5)

> * Does the debugger get loaded correctly when no target is attached? Restart VS Code to be sure
When I only connect J-Link to the computer without connecting it to the target board, it looks like this.
![下载](https://github.com/jakkra/ZSWatch/assets/56341360/d39e75f4-d18f-4e89-8f09-30893e4d504d)

> * Can you expand the debugger menu and see a target?
When I connect four pins（SWDCLK，SWDIO，GND，VTarget） to J-Link, it looks like this.
<img width="224" alt="捕获2" src="https://github.com/jakkra/ZSWatch/assets/56341360/43126306-2c06-4f18-ae44-d39f1d77ad2c">

> * Does the power supply of the target work?
> Yes, the target board is powered properly as the screen displays normally.

**Comment by Kampi** [comment]
Okay that looks good so far. Can you program the MCU?

**Comment by DREAM669** [comment]
when I click Flash Button, it shows "No connected device found with serial number 1050050002.
Either unlink the device from the build or connect that device."
I Jlink serial number is 5930563, do I need change this number?

**Comment by jakkra** [comment]
> when I click Flash Button, it shows "No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device." I Jlink serial number is 5930563, do I need change this number?

No, serial number is fixed, can't change.

Please use JFlash Lite and try do an erase in it. Also try flashing the built hex files directl using JFlashLite to see if it works. This will tell us if the debugger is working fine.

**Comment by DREAM669** [comment]
I previously used the nRF5340DK board for downloading programs to the ZSwatch, and it worked fine. The serial number (SN) of the nRF5340DK is 1050050002.

**Comment by DREAM669** [comment]
> > when I click Flash Button, it shows "No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device." I Jlink serial number is 5930563, do I need change this number?
> 
> No, serial number is fixed, can't change.
> 
> Please use JFlash Lite and try do an erase in it. Also try flashing the built hex files directl using JFlashLite to see if it works. This will tell us if the debugger is working fine.

I am able to download programs successfully using the command-line tool, which indicates that my J-Link is functional. However, I am unable to download programs and debug within VS Code.

**Comment by jakkra** [comment]
Ok, please try this:
![image](https://github.com/jakkra/ZSWatch/assets/4318648/c1b0bf9a-cf8e-4c82-8053-0552f778e88a)

Try both of those, see if one of them works
![image](https://github.com/jakkra/ZSWatch/assets/4318648/6c5eafbb-2cb2-483e-bc8c-677776ab35b9)

**Comment by DREAM669** [comment]
@jakkra
PS E:\ZSWatch-main_newbard\app> nrfjprog -f NRF53 --recover
Recovering device. This operation might take 30s.
Erasing user code and UICR flash areas.
Writing image to disable ap protect.

**Comment by jakkra** [comment]
> @jakkra
> PS E:\ZSWatch-main_newbard\app> nrfjprog -f NRF53 --recover
> Recovering device. This operation might take 30s.
> Erasing user code and UICR flash areas.
> Writing image to disable ap protect.

That looks correct, is there a question?

**Comment by DREAM669** [comment]
> > @jakkra
> > PS E:\ZSWatch-main_newbard\app> nrfjprog -f NRF53 --recover
> > Recovering device. This operation might take 30s.
> > Erasing user code and UICR flash areas.
> > Writing image to disable ap protect.
> 
> That looks correct, is there a question?

My problem is that I want to use Jlink to debug the program in VS code, but I get an error about "No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device."

**Comment by jakkra** [comment]
> 
> 
> 
> 
> > > @jakkra
> > > PS E:\ZSWatch-main_newbard\app> nrfjprog -f NRF53 --recover
> > > Recovering device. This operation might take 30s.
> > > Erasing user code and UICR flash areas.
> > > Writing image to disable ap protect.
> > 
> > That looks correct, is there a question?
> 
> My problem is that I want to use Jlink to debug the program in VS code, but I get an error about "No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device."

Did you try changing device provider as suggested?

**Comment by DREAM669** [comment]
"No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device."
Does this sentence mean that the debugging tool I set before is nRF5340DK, and I need to set the debugging tool to Jlink?

**Comment by DREAM669** [comment]
My nRF5340DK cannot work, so I can only use Jlink.

**Comment by Kampi** [comment]
> > > @jakkra
> > > PS E:\ZSWatch-main_newbard\app> nrfjprog -f NRF53 --recover
> > > Recovering device. This operation might take 30s.
> > > Erasing user code and UICR flash areas.
> > > Writing image to disable ap protect.
> > 
> > 
> > That looks correct, is there a question?
> 
> My problem is that I want to use Jlink to debug the program in VS code, but I get an error about "No connected device found with serial number 1050050002. Either unlink the device from the build or connect that device."

1050050002 is your DK? So the used device in VS Code is your DK and not the JLink. Can you please unplug the DK and plug in only the JLink to make sure that there is no issue?

**Comment by DREAM669** [comment]
Yes, 1050050002 is nRF4340DK.  I have unpluged the DK.
I guess what we have to do now is how to implement "unlink the device from the build"

**Comment by jakkra** [comment]
> Yes, 1050050002 is nRF4340DK. I have unpluged the DK. I guess what we have to do now is how to implement "unlink the device from the build"

Just click here to link/unlink
![image](https://github.com/jakkra/ZSWatch/assets/4318648/e387495f-7e92-4a34-a65a-695068e819a1)

**Comment by DREAM669** [comment]
> > Yes, 1050050002 is nRF4340DK. I have unpluged the DK. I guess what we have to do now is how to implement "unlink the device from the build"
> 
> Just click here to link/unlink ![image](https://user-images.githubusercontent.com/4318648/285133803-e387495f-7e92-4a34-a65a-695068e819a1.png)

OK! 
This problem is solved. Thank you so much！@jakkra@Kampi

**Comment by Kampi** [comment]
Glad to hear that! Enjoy the hacking 😀
