### ISSUE TITLE
NTS0104GU12 questions

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch#171]
Currently, I am facing a problem. You did not connect a pull-up resistor to your NTS0104, but I found that the signal of IIC without a pull-up resistor is unstable. After connecting the pull-up resistor, the voltage level is relatively normal.Thank you for your reply!

**Comment by Kampi** [comment]
Hi @DREAM669 

which pull-up resistors do you mean? The IC has internal pull-up resistors attached to its inputs and outputs. Please check the [datasheet](https://www.nxp.com/docs/en/data-sheet/NTS0104.pdf) on page 15 topic 14.2.

**Comment by DREAM669** [comment]
Okay, let me sort out the current issues.
1.After connecting the connector to the display screen, measure the IIC voltage. SDA and SCL changed from normal 3.3V to 2.7V and 2.5V
2. After downloading the program, the Touch function does not work. Is it due to voltage issues that the Touch chip cannot be driven?
Thank you very much for your reply!

**Comment by jakkra** [comment]
> Okay, let me sort out the current issues. 1.After connecting the connector to the display screen, measure the IIC voltage. SDA and SCL changed from normal 3.3V to 2.7V and 2.5V 2. After downloading the program, the Touch function does not work. Is it due to voltage issues that the Touch chip cannot be driven? Thank you very much for your reply!

What PCB version did you order? Because we never had a BOM with this wrong logic shifter.

**Comment by DREAM669** [comment]
Initial version PCB. The version using TXB0104 frequency conversion chip. But I soldered NTS0104 onto it again, replacing TXB0104. May I ask, after you connect the display screen, is the voltage of IIC still 3.3V? No decline? thank you.

**Comment by jakkra** [comment]
> Initial version PCB. The version using TXB0104 frequency conversion chip. But I soldered NTS0104 onto it again, replacing TXB0104. May I ask, after you connect the display screen, is the voltage of IIC still 3.3V? No decline? thank you.

Please provide the commit you used

**Comment by DREAM669** [comment]
I am using your first version. You didn't encounter this situation at the time, did you?

**Comment by DREAM669** [comment]
Okay, I understand what to do now. I will try to compare. There is only one connector on the PCB. Thank you.

**Comment by jakkra** [comment]
@DREAM669 I made many different version, so I'm not sure which one 

> Okay, I understand what to do now. I will try to compare. There is only one connector on the PCB. Thank you.

Ok, then you are here. Just see if I changed something else on the PCB, if not you may have a soldering issue.
![image](https://github.com/jakkra/ZSWatch/assets/4318648/f4a52026-4d3b-4195-9a2d-ec2ef49fcc60)

**Comment by jakkra** [comment]
> May I ask if the voltage converted by NTS0104 after connecting the display screen is 3.3V? Or is there a decrease? Thank you for your reply!

Will measure when I have a chance. May be a day or two.

**Comment by DREAM669** [comment]
Finally, it was discovered that the pin pin definition was incorrect. Thank you
