### ISSUE TITLE
Improve QSPI support

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#182]
The available Flash is running low and rev 4 is ready. So we should have an eye on this topic 👍 

**ToDo**

- [x] #153 
- [ ] Move fonts to external flash ([this](https://docs.lvgl.io/master/overview/font.html#load-a-font-at-run-time)]
- [ ] Try to move code for apps to external flash?

**Comment by vChavezB** [comment]
Just some info, apparently you do XIP from external flash :)

https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/application_development/code_relocation_nocopy
