### ISSUE TITLE
Add alarm API

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#189]
Add a way to create alarms. Zephyr's RTC emul is not good.
Need to implement something ourselves.
Want to be able to do: Call this function at 23:59:59 for example.

**Comment by Kampi** [comment]
Can be done with https://github.com/jakkra/ZSWatch-HW/issues/44

**Comment by jakkra** [comment]
Done in https://github.com/jakkra/ZSWatch/pull/355
We now have `zsw_alarm_add` and `zsw_alarm_add_timer` that handles the requirements in this issue.
