### ISSUE TITLE
Display init sequence error

### ISSUE THREAD

**Issue by amrithvenkat12** [jakkra/ZSWatch#2]
I found these errors in the display driver init sequence.
/app/drivers/display/gc9a01.c
* (line 119-121)

```
    GC9A01A1_VREG1A, 0x13,
    GC9A01A1_VREG1B, 0x13,
    GC9A01A1_VREG2A, 0x22,
```

should be

```
    GC9A01A1_VREG1A,1, 0x13,
    GC9A01A1_VREG1B,1, 0x13,
    GC9A01A1_VREG2A,1, 0x22,
```
It is missing the numArgs.

* line 112
 ``` 0xB6, 2, 0x00, 0x00,``` should be  ``` 0xB6, 2, 0x00, 0x20,```
* line 143
 ```GC9A01A_TEON, 1, GC9A01A_INVOFF,``` should be ```GC9A01A_TEON, 0,```.

In my [implementation](https://github.com/amrithvenkat12/gc9a01a_zephyr_driver/blob/main/drivers/display/display_gc9a01a.c) I have removed some redundant register inits and moved some register inits to a function call,(some registers can be initialized earlier on , like orientation and pixel format). It also has pwm based backlight control implemented. 

I hope this solves the problem that you face. 
Cheers,
Amrith

**Comment by jakkra** [comment]
Awesome, tried your driver and could remove my color workarounds. Thanks for pointing out those diffs, but something more is missing. You driver is a bit more well done, I just hacked mine together to get it up and running. Now just need to find what I'm doing different :)
