### ISSUE TITLE
CAD

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch#20]
From the picture, it can be seen that you have already made the watch case, haven't you? How beautiful! Can you share the CAD files and take a look? I am very curious about how the button part is resolved. Thank you.

**Comment by jakkra** [comment]
Yes, once I'm fully finished I will publish it, got small tuning left. Solved bottom using threaded m2 inserts, so bottom is screwed on.

**Comment by DREAM669** [comment]
> Yes, once I'm fully finished I will publish it, got small tuning left. Solved bottom using threaded m2 inserts, so bottom is screwed on.

Can you share the CAD file of the watch with me first? It's really beautiful! I am very curious about its structure. Thank you.

**Comment by DREAM669** [comment]
Especially for your buttons, are the buttons ready-made? Or 3D printing?

**Comment by jakkra** [comment]
Still printed, I did not manage to find any suitable to buy.

**Comment by jakkra** [comment]
Uploaded now
