### ISSUE TITLE
battery

### ISSUE THREAD

**Issue by DREAM669** [jakkra/ZSWatch#215]
What is the total power consumption of this watch when the screen is on?
How long can this 450mah support? Can you share the link to purchase batteries?
I tried using a 3.7V 100mAh battery and found that after 10 minutes, the screen turned off.
Looking forward to your reply!

**Comment by DREAM669** [comment]
@jakkra

**Comment by jakkra** [comment]
1. Screen on 50% brightness - ~34mA
2. 0% brightness, display chip on, touch chip on - 300uA
3. Screen off, 3V3 off - 90uA

The 2nd one the watch enters 20s after interacting with it. 
The watch will enter the 3rd state when left stationary for two minutes. 

I'm getting about a week right now from the battery on the watch. 

https://de.aliexpress.com/item/4000121983257.html?gatewayAdapt=glo2deu

**Comment by ldab** [comment]
from 100% to 40% in 12 days,  did not use it all the time:

![image](https://github.com/jakkra/ZSWatch/assets/34199302/ab0bd3a7-0a9d-4b10-a16c-abf5396b5d34)

**Comment by DREAM669** [comment]
The screen is always on now, how long does it normally go into an inactive state.

**Comment by DREAM669** [comment]
ZSW_ACTIVITY_STATE_ACTIVE,
    ZSW_ACTIVITY_STATE_INACTIVE,
    ZSW_ACTIVITY_STATE_NOT_WORN_STATIONARY,
When and how to enter and exit these three modes?

**Comment by Kampi** [comment]
I can confirm the battery life time of @ldab. I reached about 2 weeks with my watch (I used it one week and the other week it lays on my desk) and ~12 days when using it every day.

ZSW_ACTIVITY_STATE_ACTIVE -> When a motion is detected or a key is pressed (screen on)
ZSW_ACTIVITY_STATE_INACTIVE -> 20 seconds (?) without activity (key press, etc.) (screen off)
ZSW_ACTIVITY_STATE_NOT_WORN_STATIONARY -> 15 minutes inactive (screen and sensors off)

@jakkra please correct me when I´m wrong :)

**Comment by jakkra** [comment]
> @jakkra please correct me when I´m wrong :)
> 
ZSW_ACTIVITY_STATE_NOT_WORN_STATIONARY -> 15 minutes inactive (screen and sensors off)
It's 160 seconds, not 15 minutes.

> But my screen is always on, maybe it's always in ZSW_ Activity_ DATE_ Do I need to modify the code or configuration file to automatically switch modes in the Active mode?

1. Check Settings -> Display -> "Display always on" And make sure it's off (this is default)
2. Go to "System Info" application and check the "Time to inactive", it should count from 20s down to 0 and then screen should turn off.

**Comment by DREAM669** [comment]
Thank you for your reply!
