### ISSUE TITLE
Sharing of your ZSwatch project 

### ISSUE THREAD

**Issue by aeonSolutions** [jakkra/ZSWatch#234]
Hi @jakkra
Great project
Just to let you know I'm sharing you ZSwatch smartwatch project on my own health and wellbeing project here on GitHub
[https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home%20Automation%20Safety%20%26%20Health%2Freadme.md](https://github.com/aeonSolutions/PCB-Prototyping-Catalogue/blob/main/Home%20Automation%20Safety%20%26%20Health%2Freadme.md)

**Comment by Kampi** [comment]
Feel free to share it :)
