### ISSUE TITLE
Weather app and fetching weather over http

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#278]
The weather integration in gadgetbridge requested an external extra app and for me it's not reliable. 

Fetch weather data using the Gadgetbridge HTTP functionality from some suitable weather API.

Should display a forecast of a few days also.

Maybe pressing on weather icon on a watchface should open the weather app. 

- Icons possibly use: https://github.com/roe-dl/weathericons/tree/master/weathericons-filled
- https://open-meteo.com/ free for open source and no API key needed - Perfect for US!
  - [Example request](https://api.open-meteo.com/v1/forecast?latitude=55.6059&longitude=13.0007&current=temperature_2m,apparent_temperature,weather_code&daily=weather_code,temperature_2m_max,temperature_2m_min,apparent_temperature_max,apparent_temperature_min,precipitation_sum,rain_sum,precipitation_probability_max&timezone=Europe%2FBerlin&forecast_days=3) 
  - Drawback, seem to want long + lat and not a Location. Makes input it harder. Maybe GB sends position?

**Comment by jakkra** [comment]
Let's borrow the design from Android :) Think it looks quite nice
![Screenshot_2024-05-16-12-29-04-95_40deb401b9ffe8e1df2f1cc5ba480b12~2](https://github.com/jakkra/ZSWatch/assets/4318648/fd925249-7990-4012-90d8-93fdc63cd074)

**Comment by Kampi** [comment]
Uh that looks quite nice
