### ISSUE TITLE
Funkytown_song not used

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#284]
https://github.com/jakkra/ZSWatch/blob/8152f4b07cb735c87b3477adf24a910605150c7b/app/src/drivers/zsw_buzzer.c#L74

**Comment by Kampi** [comment]
@jakkra can I remove it or do you want to keep it?

**Comment by jakkra** [comment]
Remove

Den mån 27 maj 2024 kl 09:09 skrev Daniel Kampert ***@***.***
