### ISSUE TITLE
Enable POSIX API in proj.conf

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#298]
Is this right @jakkra?

https://github.com/jakkra/ZSWatch/blob/b271ddf0f0f5cf526ab90f48a0818229dc588006/app/prj.conf#L158

Imo it should be removed there and moved completely to `native_posix.conf`

**Comment by jakkra** [comment]
Nope, this is correct I think, posix api gives the time functions etc for example I think. This is unrelated to native posix.

But you can try and see if it builds without, of so then it can be removed.

**Comment by Kampi** [comment]
You are right :)
