### ISSUE TITLE
Build  latest Master error 

### ISSUE THREAD

**Issue by tianmaduxing** [jakkra/ZSWatch#351]

**Comment by tianmaduxing** [comment]
It's better after west update

But now:
C:/Repos/ZSWatch/app/src/ui/watchfaces/73_2_dial/zsw_watchface_73_2_dial_ui.c:9:10: fatal error: lvgl.h: No such file or directory
    9 | #include <lvgl.h>

**Comment by jakkra** [comment]
> It's better after west update
> 
> But now: C:/Repos/ZSWatch/app/src/ui/watchfaces/73_2_dial/zsw_watchface_73_2_dial_ui.c:9:10: fatal error: lvgl.h: No such file or directory 9 | #include <lvgl.h>

Make sure you do a pristine build as you built once without west update correctly done. Also please share full log. It's compiling on ci so it's probably something with your setup that's wrong.
