### ISSUE TITLE
esim support or sim 

### ISSUE THREAD

**Issue by wanghaisheng** [jakkra/ZSWatch#365]
I dont know if this is right place to ask

**Comment by Kampi** [comment]
Hi,

what exactly is the question? Why do we need an eSIM?

**Comment by wanghaisheng** [comment]
let me clarify, I want a 4g version

**Comment by Kampi** [comment]
That´s currently not an option and not on our agenda. But you can do it on your own.

**Comment by wanghaisheng** [comment]
can you point out a direction? any helps is appreciated

**Comment by jakkra** [comment]
Chek in the HW repo for the kicad files. It will be hard to fit a cellular module. Maybe with double sided assembly, otherwise some other stuff needs to be removed/reedesigned.
