### ISSUE TITLE
Config to allow touch chip to wake up the screen

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#41]
The touch chip IC cst816s have features to go into low power mode and then allow wakeup by doing gestures or taps on the screen. This would be a nice additional way to wake up the watch.

Implement this. What registers and how to configure this needs some digging as much documentation for the cst816s is in chinese.

**Comment by Kampi** [comment]
Non chinese datasheet:

https://www.waveshare.com/w/upload/5/51/CST816S_Datasheet_EN.pdf

**Comment by jakkra** [comment]
[CST816S_20190508_en-US.pdf](https://github.com/jakkra/ZSWatch/files/12843602/CST816S_20190508_en-US.pdf)
Auto translated to english parts of another datasheet.
