### ISSUE TITLE
Bosch BME688 BSEC library. Allows for air quality measurement and more.

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#42]
This is a binary blob and shall be optional to use (opt-in)

This blob needs to be downloaded from here by each person compiling (I think): https://www.bosch-sensortec.com/software-tools/software/bsec/ 

But this blob allows for the advanced features of the BMP588, such as air quality etc.

- Integrate this library and add functions to get this data
- Document how to set this up (download, where to put the lib etc.)

**Comment by vChavezB** [comment]
Good to know about this. Since I already have soldered a board with the BME688 if I have some time I will try to check this out. My use case is testing on my fridge and knowing if food goes bad 😄

**Comment by Kampi** [comment]
The Bosch BSEC library is added to the firmware, together with an application to visualize the IAQ index.

![Image](https://github.com/jakkra/ZSWatch/assets/3458587/124e59c8-d53c-4e1f-9e31-99d13c4af333)
