### ISSUE TITLE
Received notifications should be propogated as zbus event. 

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#48]
Remove the callback used here https://github.com/jakkra/ZSWatch/blob/main/app/src/ble_comm.c#L535C5-L535C19 and use ZBUS event instead also for notifications.

In order to know when all subscribers and listeners are done with the event, see this approach here: See example how to do it here: https://github.com/zephyrproject-rtos/zephyr/pull/59071/files

**Comment by ldab** [comment]
Is this still relevant? Otherwise it would be better to do it before #61

**Comment by Kampi** [comment]
@jakkra does it make sense to propagate also the connected and disconnected callbacks via ZBUS? I can do the ZBUS change if it´s okay because the sensor subsystem modification also needed some stuff for ZBUS and then I can add the BLE stuff too.

**Comment by jakkra** [comment]
Sure, but be careful of context of the notifications, I think that's why they are not yet distributed over zbus, as they can be overwritten. @Kampi read this https://discord.com/channels/720317445772017664/1042530682011926631/1113790721133129738 first

**Comment by jakkra** [comment]
> Is this still relevant? Otherwise it would be better to do it before #61 

Hmm, they touch the same code, but the order doesn't really matter. If notifications are sent over zbus or callback it's just a few lines of common code, so I think they can be worked on in parallel also. Or any order.

**Comment by Kampi** [comment]
IMO you can start working on the iOS stuff because the sensor testing and the ZBUS modification will need some time.

**Comment by jeffwelder-ellenbytech** [comment]
If you have not checked out the new message subscriber feature of zbus it might be worth looking at. 😄 

`ZBUS_MSG_SUBSCRIBER_DEFINE()` 
https://docs.zephyrproject.org/latest/services/zbus/index.html

**Comment by Kampi** [comment]
Thanks @jeffwelder-ellenbytech 

I will take a look at it.

**Comment by jakkra** [comment]
> If you have not checked out the new message subscriber feature of zbus it might be worth looking at. 😄
> 
> `ZBUS_MSG_SUBSCRIBER_DEFINE()` https://docs.zephyrproject.org/latest/services/zbus/index.html

Looks interesting, but from what I see it requires a thread with stack for each subscriber, which is what I want to avoid as it wastes alot of RAM. Best would be to always use the system work queue for all messages, but not exactly sure how to implement that.

**Comment by Kampi** [comment]
@ldab I added ZBUS to the `BLE_enhancements#124` branch and tested it with GadgetBridge and a subscriber and it looks good.

![image](https://github.com/jakkra/ZSWatch/assets/3458587/da1b059e-ea23-435e-a46b-bffb951a9a1a)

I´ve added it also to the Apple Notification service. If you have time, can you please test it? :)

**Comment by ldab** [comment]
It looks like the content/title/body is missing or got lost, it was supposed to print

mobile phone
Incoming call

![image](https://github.com/jakkra/ZSWatch/assets/34199302/13ee047a-4b7e-4976-aa2c-22feeeb66306)

**Comment by jakkra** [comment]
> @Kampi maybe this change you did that caused this issue https://github.com/jakkra/ZSWatch/blob/main/app/src/main.c#L358
> 
> body => sender (I guess it's not populated the same in iOS code)

I'm fixing it now

**Comment by Kampi** [comment]
Yeah was a bad testing by me because I only tested it with Gadgetbridge
