### ISSUE TITLE
Hello, author.Is v1 available???

### ISSUE THREAD

**Issue by mrz5802** [jakkra/ZSWatch#5]

**Comment by jakkra** [comment]
Hi, availible for what? It requires some fixes to really be easily useful, this will be addressed in v2. You can see my progress here: https://github.com/users/jakkra/projects/1/views/5

**Comment by freasy** [comment]
> Hi, availible for what? It requires some fixes to really be easily useful, this will be addressed in v2. You can see my progress here: https://github.com/users/jakkra/projects/1/views/5

This project is not visible to the public.

**Comment by jakkra** [comment]
@freasy oh thought it was public, fixed now!
