### ISSUE TITLE
Use Zephyr retention subystsem for RAM retention instead of the current way.

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#56]
Today it's done here: https://github.com/jakkra/ZSWatch/blob/main/app/src/ram_retention_storage.c

Should be using the Zephyr subsystem instead: https://docs.zephyrproject.org/latest/services/retention/index.html

**Comment by ldab** [comment]
@jakkra should close?

1bc8a82f16e5ae9ed863e41b54364b40049c3764
