### ISSUE TITLE
Try out some HTTP requests from the watch through Gadgetbridge. Maybe an app to demonstrate

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#58]
![image](https://github.com/jakkra/ZSWatch/assets/4318648/5219bcd6-ed2d-443b-9c9b-7b0e4f31ab13)

**Comment by ldab** [comment]
Note to self https://www.espruino.com/Gadgetbridge#http-requests

**Comment by Kampi** [comment]
@ldab can you please add your applications to the project `Kconfig` so it´s possible to enable / disable those?

**Comment by ldab** [comment]
Do you mean all of them or just this one?

**Comment by Kampi** [comment]
Both your Power Point app and the speedometer :)

**Comment by ldab** [comment]
https://github.com/jakkra/ZSWatch/pull/166
