### ISSUE TITLE
Question: Why is battery superviser?

### ISSUE THREAD

**Issue by Aukstkalnis** [jakkra/ZSWatch#6]
Hello, I am very interested in your project. I am planning to build something similar but with AMOLED display and with internal small coin battery for RTC time. I am just  curious why would you use battery supervisor chip? From your photos I can see that the battery has already integrated supervisor, so why you adding additional?

**Comment by jakkra** [comment]
Hi, the issue with some (many?) of those lipo batteries is that they only cut power to itself at a very very low level, doing this (repeatedly) will damage the battery.

**Comment by Aukstkalnis** [comment]
So technically, battery manager circuit that is on a battery  is not needed and can be removed. Right?

**Comment by jakkra** [comment]
> So technically, battery manager circuit that is on a battery is not needed and can be removed. Right?

Still for example the battery management IC still consumes like 0.5-1uA or something, so eventuelly battery may drain and there is still a use for the battery manager circuit in the battery too. I'm not very familiar with how those integrated battery managers work, probably depends on manufactuer also.

**Comment by Aukstkalnis** [comment]
OK, cool. I think it is reasonable to have backup IC for battery cut of :) Thanks for your quick replay :)
