### ISSUE TITLE
Indicate some way that charging started

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#69]
For example UI popup or a small vibration.

Info already published on `ZBUS_CHAN_DECLARE(chg_state_data_chan);`

**Comment by Kampi** [comment]
@jakkra we have to think about a solution for how this should be handled with rev 5. I don´t think that this can be done with Device Tree only, because currently the input subsys is used for it, and with rev 5 the nPM1300 driver handles this.

**Comment by jakkra** [comment]
@Kampi  I think we remove it for < v5, I'll do a PR
