### ISSUE TITLE
Use sysbuild to build MCUBoot and nRF5340 net core application

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#77]
References:
https://github.com/zephyrproject-rtos/zephyr/tree/main/samples/application_development/sysbuild/with_mcuboot
https://docs.zephyrproject.org/latest/build/sysbuild/index.html

**Comment by Kampi** [comment]
@jakkra is this still relevant? NET core app is already build with NCS

**Comment by jakkra** [comment]
Yeah I guess we stick with ncs now, so yes can close
