### ISSUE TITLE
APDS 9306 065 light sensor driver

### ISSUE THREAD

**Issue by jakkra** [jakkra/ZSWatch#78]
Needed for rev 3 ZSWatch
`zsw_light_sensor.c` contains just code for reading chip ID right now.
Write a proper driver for it.

**Comment by Kampi** [comment]
The first iteration of the driver is ready to be used.

**TODO**
- Remove PM code, because the IC doesn´t have any advanced PM features
- Add IRQ support (not mandatory for the watch)
- Add conversion from bin to Lux?
