### ISSUE TITLE
Rework button and touch handling

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#87]
**Idea**

- Use the input subsystem to handle all events (touch and buttons)
- Create a driver for LVGL that contains the input subsystem handling. So we are able to control the inputs that are passed to LVGL
- Apply different key IDs to all buttons

![Image](https://github.com/jakkra/ZSWatch/assets/3458587/04758f8d-f7f3-40cf-9aa9-1bbcaeefaf07)

**References**

https://docs.zephyrproject.org/latest/services/input/index.html#c.INPUT_CALLBACK_DEFINE
https://docs.zephyrproject.org/latest/build/dts/api/bindings/input/zephyr,input-longpress.html

**Comment by jakkra** [comment]
@Kampi Can be closed?
