### ISSUE TITLE
Add condition to enable file system in configuration for rev 3 and above

### ISSUE THREAD

**Issue by Kampi** [jakkra/ZSWatch#95]
`CONFIG_FILE_SYSTEM` and `CONFIG_LV_Z_USE_FILESYSTEM` in `proj.conf` (or somewhere else) should only be set to `y` by default if the target is rev 3 or above. Can we add a revision-specific configuration?

**Comment by jakkra** [comment]
It's already: https://github.com/jakkra/ZSWatch/blob/main/app/boards/arm/zswatch_nrf5340/zswatch_nrf5340_cpuapp_3.conf#L19
For rev 4, a new copy of this file should be added and called _4.conf.

Was it something else you whee after? Unfortunately you cannot have conditional logic directly in `prj.conf`

**Comment by Kampi** [comment]
Great. Should be a perfect solution.
